name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '20'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: backend

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
  
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
        
      - name: Build frontend
        run: npm run build --no-progress 2>&1 >/dev/null || true
        working-directory: frontend  

  start_database:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start PostgreSQL
        run: |
          docker run -d --name my-postgres -e POSTGRES_PASSWORD=postgres_pwd -p 5432:5432 postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          
  start_backend:
      runs-on: ubuntu-latest
      needs: [build_backend, start_database]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: List contents of quarkus-app directory
          run: |
            ls -R backend/

        - name: Start Quarkus Backend
          run: |
            java -jar target/quarkus-app/quarkus-run.jar
          working-directory: backend
